# Generated by Django 5.0.4 on 2024-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_rename_create_task_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
